app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search_result, name='search_result'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
 
urlpatterns = [
    path('', views.all_products, name='all_product'),
    path('<slug:product_slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class ValidManager(models.Manager):
    def get_queryset(self):
        return super(ValidManager, self).get_queryset().filter(available=True)

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    
    valid_objects = ValidManager()
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
 
    def __str__(self):
        return '{}'.format(self.name)
    
    def get_url(self):
        return reverse('shop:product_detail', args=[self.slug])

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
 
    return render(request, 'cart/cart.html', dict(cart_items = cart_items, total = total, counter = counter))


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
                cart_id =  _cart_id(request)
            )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search_result(request):
    products = None
    query = None
    
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
 
    return render(request, 'search.html', {'query': query, 'products': products})

shop/views.py
from django.shortcuts import render
from shop.models import Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def all_products(request):
    products_list = Product.valid_objects.all()
    
    paginator = Paginator(products_list, 3)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
 
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'shop/product_list.html', {'products': products})


def product_detail(request, product_slug):
    try:
        product = Product.objects.get(slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product_detail.html', {'product': product})

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
    This is the shopping cart page.. Proced to review your items and place the order.
{% endblock %}
{% block title %}
    Cart - Various Product Store
{% endblock %}
{% block content %}
    {% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text center my_title">Your shopping cart is empty</h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'shop:all_product' %}">here</a> to continue shopping.
        </p>
    </div>
</div>
    {% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
    </div>
    <br>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td><a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a></td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Unit Price: ￡{{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x ￡{{cart_item.product.price}}
                    </td>
                    <td>
                        ￡{{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                            <i class="fas fa-plus-circle custom_icon"></i>
                        </a>
                         
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fas fa-minus-circle custom_icon"></i>
                        </a>
                         
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_item">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                    {% else %}
                    <td>
                         
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fas fa-minus-circle custom_icon"></i>
                        </a>
                         
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_item">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                    <td></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your shopping cart item before proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your total is: <strong>￡{{ total }}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:all_product' %}" class="btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
<br>
    {% endif %}
{% endblock %}

search/templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block matadescription %}
    We have a variety of stunning and comfy cushions. Lock for the one that suits your needs.
{% endblock %}
{% block title %}
    Search - Perfect Cushion Store
{% endblock %}
{% block content  %}
    <div>
        <p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
    </div>
    <div class="container">
        <div class="row mx-auto">
            {% for product in products  %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>£{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found.</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="description" content="{% block metadescription %}{% endblock %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; 2020 Takahashi Takuya</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="Perfect Cushion Store" width="100" height="100" class="rounded-circle">
    </center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
 
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Shop
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop:all_product' %}">All Products</a>
                    {% for product in products %}
                    <a class="dropdown-item" href="{{product.get_url}}">{{product.name}}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i></a>
            </li>
            {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">({{item_count}})</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search:search_result' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

shop/templates/shop/product_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
{{ product.name }} - Perfect Cushion Store
{% endblock %}
{% block content %}

<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'shop:all_product' %}">Home</a>|<a href="{{ product.get_url }}">{{product.name}}</a></p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem">
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p>￡{{product.price}}</p>
                    <p class="my_title">Product Description</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

shop/templates/shop/product_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
   {% if category %}
{{ category.description|truncatewords:155 }}
   {% else %}
        Welcome to the cushion store where you can buy comfy and awesome cushions.
   {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
{{ category.name }} - Perfect Cushion Store
   {% else %}
        See Our Cushion Collection - Perfect Cushion Store
   {% endif %}
{% endblock %}
{% block content %}
 
<div class="row mx-auto my-2">
    <div class="col-12">
        <img src="{% static 'img/banner.jpg' %}" alt="Our Products Collection" class="w-100">
    </div>
</div>
<br>
<div class="row">
    <div class="col-12">
        <h1>Our Products Collection</h1>
        <p>Finding the perfect cushion for your room can instantly add to the levels of comfort and sense of style throughout your home.</p>
    </div>
</div>
 
<div class="row">
    {% for product in products %}
    <div class="col-4">
        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}" width="300" height="200"></a>
 
        <div>
            <h4>{{product.name}}</h4>
            <p>£{{product.price}}</p>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row">
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}